swagger: "2.0"
info:
  title: polymarket/v1/health.proto
  version: version not set
tags:
  - name: HealthAPI
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/health:
    get:
      summary: Health check
      description: Check service health status
      operationId: HealthAPI_HealthCheck
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HealthCheckResponse'
      tags:
        - Health
definitions:
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        type: string
