swagger: "2.0"
info:
  title: polymarket/v1/orderbook.proto
  version: version not set
tags:
  - name: OrderBookAPI
basePath: /rest/api/
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/orderbook/{symbol}:
    get:
      summary: Get order book
      description: Returns the current aggregated order book for a symbol
      operationId: OrderBookAPI_GetOrderBook
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetOrderBookResponse'
      parameters:
        - name: symbol
          description: Instrument symbol (e.g., "BTC-USD")
          in: path
          required: true
          type: string
        - name: depth
          description: Number of price levels to return (default 3, max 10)
          in: query
          required: false
          type: integer
          format: int32
      tags:
        - OrderBook
  /v1/orderbook/{symbol}/bbo:
    get:
      summary: Get best bid/offer
      description: Returns the top of book (best bid and offer) for a symbol
      operationId: OrderBookAPI_GetBBO
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetBBOResponse'
      parameters:
        - name: symbol
          description: Instrument symbol (e.g., "BTC-USD")
          in: path
          required: true
          type: string
      tags:
        - OrderBook
definitions:
  v1BookEntry:
    type: object
    properties:
      px:
        type: string
        format: int64
      qty:
        type: string
        format: int64
      symbolSubType:
        type: string
    description: BookEntry lists a price and volume for a market data record.
  v1GetBBOResponse:
    type: object
    properties:
      symbol:
        type: string
        title: Instrument symbol
      bestBid:
        $ref: '#/definitions/v1BookEntry'
        title: Best bid (highest buy price)
      bestOffer:
        $ref: '#/definitions/v1BookEntry'
        title: Best offer (lowest sell price)
      spread:
        type: string
        format: int64
        title: Spread in price units (best_offer.px - best_bid.px)
      midPrice:
        type: string
        format: int64
        title: Mid price ((best_bid.px + best_offer.px) / 2)
      state:
        $ref: '#/definitions/v1InstrumentState'
        title: Current trading state of the instrument
      transactTime:
        type: string
        format: date-time
        title: Server timestamp of the data
    description: Response containing the best bid and offer.
  v1GetOrderBookResponse:
    type: object
    properties:
      symbol:
        type: string
        title: Instrument symbol
      bids:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1BookEntry'
        title: Bid side of order book (sorted by price descending)
      offers:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1BookEntry'
        title: Offer/ask side of order book (sorted by price ascending)
      state:
        $ref: '#/definitions/v1InstrumentState'
        title: Current trading state of the instrument
      stats:
        $ref: '#/definitions/v1InstrumentStats'
        title: Market statistics (last trade, open/high/low/close, etc.)
      transactTime:
        type: string
        format: date-time
        title: Server timestamp of the data
    description: Response containing the order book snapshot.
  v1InstrumentState:
    type: string
    enum:
      - INSTRUMENT_STATE_OPEN
      - INSTRUMENT_STATE_PREOPEN
      - INSTRUMENT_STATE_SUSPENDED
      - INSTRUMENT_STATE_EXPIRED
      - INSTRUMENT_STATE_TERMINATED
      - INSTRUMENT_STATE_HALTED
      - INSTRUMENT_STATE_MATCH_AND_CLOSE_AUCTION
    description: InstrumentState represents the state of an instrument.
  v1InstrumentStats:
    type: object
    properties:
      openPx:
        type: string
        format: int64
        x-nullable: true
      closePx:
        type: string
        format: int64
        x-nullable: true
      lowPx:
        type: string
        format: int64
        x-nullable: true
      highPx:
        type: string
        format: int64
        x-nullable: true
      lastTradePx:
        type: string
        format: int64
        x-nullable: true
      indicativeOpenPx:
        type: string
        format: int64
        x-nullable: true
      settlementPx:
        type: string
        format: int64
        x-nullable: true
      sharesTraded:
        type: string
        format: int64
        x-nullable: true
      notionalTraded:
        type: string
        format: int64
        x-nullable: true
      openInterest:
        type: string
        format: int64
        x-nullable: true
    description: InstrumentStats contains statistics about an instrument.
